name: Build and Scan Minecord Image

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Buildah Build
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: minecord
        tags: latest ${{ github.sha }}
        containerfiles: ./Containerfile

    - name: Push To quay.io
      id: push-to-quay
      if: github.event_name == 'push'
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/jdcasey
        username: ${{ secrets.QUAY_BOT_USER }}
        password: ${{ secrets.QUAY_BOT_PASSWORD }}
