name: Build and Scan Minecord Image

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Scan for python vulnerabilities
      uses: aquasecurity/trivy-action@0.20.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'library'
        severity: 'CRITICAL,HIGH'

    - name: Buildah Build
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: minecord
        tags: latest ${{ github.sha }}
        containerfiles: ./Containerfile

    - name: Push To quay.io
      id: push-to-quay
      if: github.event_name == 'push'
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/jdcasey
        username: ${{ secrets.QUAY_BOT_USER }}
        password: ${{ secrets.QUAY_BOT_PASSWORD }}
